/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-tint": "#565e74",
          "tertiary": "#000000",
          "surface-bright": "#f8f9ff",
          "surface-container-lowest": "#ffffff",
          "secondary-fixed": "#6ffbbe",
          "inverse-surface": "#213145",
          "on-tertiary": "#ffffff",
          "on-surface": "#0b1c30",
          "primary-fixed": "#dae2fd",
          "on-tertiary-fixed-variant": "#574425",
          "secondary-fixed-dim": "#4edea3",
          "surface-variant": "#d3e4fe",
          "tertiary-fixed-dim": "#dec29a",
          "tertiary-fixed": "#fcdeb5",
          "outline-variant": "#c6c6cd",
          "tertiary-container": "#271901",
          "on-primary-container": "#7c839b",
          "on-primary-fixed": "#131b2e",
          "background": "#f8f9ff",
          "error": "#ba1a1a",
          "secondary": "#006c49",
          "primary": "#000000",
          "on-background": "#0b1c30",
          "surface-container-highest": "#d3e4fe",
          "secondary-container": "#6cf8bb",
          "outline": "#76777d",
          "on-tertiary-container": "#98805d",
          "on-secondary-fixed-variant": "#005236",
          "on-surface-variant": "#45464d",
          "on-tertiary-fixed": "#271901",
          "inverse-on-surface": "#eaf1ff",
          "surface": "#f8f9ff",
          "on-secondary-container": "#00714d",
          "surface-dim": "#cbdbf5",
          "on-secondary-fixed": "#002113",
          "surface-container-low": "#eff4ff",
          "inverse-primary": "#bec6e0",
          "surface-container": "#e5eeff",
          "primary-fixed-dim": "#bec6e0",
          "surface-container-high": "#dce9ff",
          "primary-container": "#131b2e",
          "on-error": "#ffffff",
          "error-container": "#ffdad6",
          "on-primary": "#ffffff",
          "on-primary-fixed-variant": "#3f465c",
          "on-secondary": "#ffffff",
          "on-error-container": "#93000a"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "lg": "24px",
          "xs": "4px",
          "container-margin": "24px",
          "base": "4px",
          "xl": "32px",
          "sm": "8px",
          "gutter": "16px",
          "md": "16px"
      },
      "fontFamily": {
          "label-sm": ["JetBrains Mono", "monospace"],
          "body-sm": ["Geist", "sans-serif"],
          "body-md": ["Geist", "sans-serif"],
          "body-lg": ["Geist", "sans-serif"],
          "display-lg": ["Geist", "sans-serif"],
          "headline-sm": ["Geist", "sans-serif"],
          "headline-md": ["Geist", "sans-serif"],
          "label-md": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
          "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500"}],
          "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
          "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "display-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "headline-sm": ["18px", {"lineHeight": "26px", "fontWeight": "500"}],
          "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}

